### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by mambax7** [fvilers/ulid.net#1]
FYI: @Lewiscowles1986 just violated your MIT License by using your code but changing the license to AGPL:
https://github.com/Lewiscowles1986/php-ulid/issues/17

I find it very disrespectful to the spirit of Open Source and to your work :( 

I hope, he'll come to his senses and will change it back to MIT, or you might contact the Free Software Foundation (https://softwarefreedom.org/) and ask them to explain to him the legal violation.

**Comment by Lewiscowles1986** [comment]
What a dick. Also it's not your MIT license as the code is not in this language. It uses {x}Unit style tests and the same data. It's not a competing library, it gains no revenue and loses you no revenue. This is basically harassment

**Comment by mambax7** [comment]
@Lewiscowles1986 it's not about money, it's not about a "competing" library, it's about integrity within the Open Source community, that we respect each other licenses and code.  If we give our code away for free, the least the we should expect is respect for our licences. 
Let's face it - you wouldn't like if somebody had taken your AGPL code and released it under something else, right?
So don't act so offended, read the explanation of MIT License:
https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html
and rewrite the test code so it's yours and release it under AGPL, or include the MIT license with it.
I do applaud you for giving credit to both JS and .NET implementations, but by your own admission:
![image](https://user-images.githubusercontent.com/613686/38783710-de36c96e-40d3-11e8-82a8-920ae8843d7f.png)

you've "borrowed" the test code from the .NET implementation, then the code is still under MIT and it should be clearly noted, incl. the copyright and the license.

**Comment by Lewiscowles1986** [comment]
> the least the we should expect is respect for our licences.

If anyone is thinking Oh, this guy made .NET code work on PHP, then relicensed. No I didn't port .NET framework to PHP just to get a library, then use your code or compiled libraries from PHP. 

OP is both showing total lack of understanding on licensing and coding; as well as being a total PITA. They have also done this for the JS version of the library.  

Their concern is that they cannot dictate the license of the PHP version of MY library. OpenSource is not about this. It's not about commanding programmers to do your bidding, whoever you are. If you'd like a programmer to listen to you, not block you, report you to github, then try to work with them, fork (if possible), or do a rewrite. 

OP is not a contributor to the JS, .NET, PHP, or Java ULID. They don't even understand that there are numerous ways to get around even the AGPL license (sadly), or that it protects their rights to access and modify the source so long as it and anything directly including it remains licensed under AGPL. This is actually something their PR attempted to violate, but I'm going to say neither FSF or myself felt the need to publicly slander or harass them about.

The licensing of MY projects is not up for discussion, there has been no theft of code or tests. OP is just displaying some form of breakdown and tagging me to harass me, which I've started documenting.

Yes my library and understanding of ULID was influenced by reading your code. Thank you Author and sole contributor :+1: :fireworks:  :100: :tada:. No I have not verbatim lifted your code.

I Certainly hope the owner of this repo can close and lock this thread to stop me being harassed and slandered further.

**Comment by mambax7** [comment]
@Lewiscowles1986 You still need to learn so much more about Open Source and about licensing. 

1) You've acknowledged yourself that you have "borrowed" the .NET tests.  The fact is that you were able to modify them for your needs because the MIT license allowed you to do so under the condition that the copyright and the license will remain there. But where is the MIT license in your package? It would be very easy for you to just say: "My code is under AGPL, and the tests are under MIT". That's where you're failing in understanding the concept of Open Source and how to respect each other!  

2) It comes across very disingenuous from you when you benefit from all the code released under MIT, you "borrow" it, modify it and incorporate in your code, but want to release "your" package under the more restrictive AGPL license.  Do you really believe that your code is more important and needs more protection/restrictions than the code from all the other people that you used and benefited from? 

3) And stop whining about slander because you obviously have no ideas what you're talking about. Go and read the definition of "slander" and then we'll talk, OK? 

And read finally the legal explanation of the MIT license so you understand better your obligation resulting from "borrowing" the code:
https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html

**Comment by Lewiscowles1986** [comment]
Are you insane? Use git log. It has never been MIT, it was AGPL from initial commit. a PR accidentally changed composer.json to report AGPL-1.0 (not from me) once upon a time. 

Everything about OP original issue and this shows their incompetence, the fact they neither understand licensing, or software.

> Both originals (JS and #NET) are using MIT license, but you switched to AGPL?

My repo isn't in JS or .NET. The one you're complaining about is written in PHP, it's always (from initial commit) been AGPL.

> Why? This makes difficult to use both JS and PHP versions :(

This imbecile doesn't know how to make a tiny wrapper so that the AGPL code isn't linked to their project, that is their problem. For a start as AGPL isn't statically linked to JS, the license incompatibility is a non-issue. The repo works for non-binary ULID, HTTP is a text protocol, OP if they were not so stupid could read a computer science book, realize they could message between using HTTP. OP's obligations under AGPL are only to share their modifications, and make available (NEON LIGHTS IF YOU DON'T MODIFY IT, MY REPO PROVIDES THIS) the source to users to preserve end-user freedom. IF you modify a thing I wrote, you have to give users the source to the ULID you use (which will probably remain unmodified because it's an externally defined standard).

> It would be nice to respect the original licenses and also release it under MIT

This seems like you know that my original license is a separate issue to releasing MY code under MIT. Regardless of your understanding because it's not my concern. None of my code for this repo ever was or is MIT. It's written in a different language to the libraries you've SPAMMED and DEFAMED me via.

OP is the worst example of a human interacting with Open Source. Too Stupid to act rationally or realise the depth of their own stupidity. ULID's generated by the libraries I wrote have no license, just the library code itself in source and compiled form.

I am deeply saddened I have to give a public lesson to this GOON for FREE, but as nobody is policing their own repo's and GitHub has yet to act, screw it, FUCK YOU GUY! As the JS library mentioned ULID as a protocol was released under the GPL. Why are you not trolling others about MIT? (DONT DO THAT, YOUR BEHAVIOUR IS UNACCEPTABLE, YOU SHOULDN'T BE ALLOWED ON A COMPUTER UNSUPERVISED)

I don't know what kind of head injury it takes to behave how you have but if you worked in close proximity to me you'd be thrown out of the building, possibly arrested and definitely face a civil suit. 

GO AWAY 

STOP TAGGING ME IN MESSAGES

YOU'LL NOTICE I'M NOT AND NEVER HAVE TAGGED YOU

**Comment by mambax7** [comment]
@Lewiscowles1986  Dude, you need to relax and start acting professionally. You're just embarrassing yourself with your foul language, your shouting, your whining, and your threats!  That's so childish! 
You obviously: 

- don't understand what "slander" or "defamation" is and how they work, 
- don't understand how Open Source licenses work, 
- and based on your previous comment, you naively believe that as long as there is no revenue loss, you can use any Open Source code any way you want, including changing the MIT license to a license of your choice:

> It's not a competing library, it gains no revenue and loses you no revenue. 

So for the 10th time - if you write the code yourself, you can release it under any license you want.  That's your right and nobody is taking it away from you. But when you "borrow" (YOUR words, not mine) somebody else's code and modify it for your needs, then you need to respect the original license under the code was released.  Otherwise somebody could take your AGPL code, make some changes, and release it under MIT, and I don't think that you would be happy about it! 

**“Don't do unto others what you don't want done unto you.”**

And please read finally the legal explanation of the MIT license so in the future you understand better your obligation resulting from "borrowing" code from somebody else:
https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html

Have a nice day!  :)

**Comment by fvilers** [comment]
Hi guys! First of all, I'd like to everyone to calm down just a bit.

@Lewiscowles1986, if you have copied/translated the test from this project into yours, even into another language, I'm afraid that you have to respect the same license than the original project. As far as I remember, the tests I wrote in the .NET port was also largely inspired from the [original version of the JS library](https://github.com/ulid/javascript/blob/master/test.js).

In today's developer lifes, I'm sure we all use OSS and are happy that open and/or free software exists. Far from me the idea of wanting to make big speech, but I'm pretty sure that the current IT ecosystem could have never been so various and developed without it. And this variety and quality comes with the respect of the original license.

I'm not a license specialist, and I'm asking @Lewiscowles1986 if he wouldn't mind to reply here what are the advantages of putting his library under AGPL vs MIT.

By the way, thanks to @mambax7 for reporting this issue.

**Comment by Lewiscowles1986** [comment]
You're incorrect and it's not happening I'd take a look at the tests if I were you, but TBH IDC, it's not changing

**Comment by Lewiscowles1986** [comment]
OH and stop tagging me in issues

**Comment by Lewiscowles1986** [comment]
https://www.copyscape.com/compare.php says there is 0% similarity between the two

* https://raw.githubusercontent.com/fvilers/ulid.net/master/Src/UlidNet.Tests/UlidTest.cs
* https://raw.githubusercontent.com/Lewiscowles1986/php-ulid/master/tests/BaseTest.php

The reason the text that has been pointed out is there is that I was looking for values to compare implementations. I cannot believe you both tagged me (which I've asked previously not to happen), then thought you had any authority to tell me what to do with code I've written. How dare you!

**Comment by mambax7** [comment]
@Lewiscowles1986  You've said  yourself that you have "borrowed" the tests from the .NET implementation:
![image](https://user-images.githubusercontent.com/613686/38828948-9c57ad26-4185-11e8-84cb-73b984ec0d42.png)

Now you're trying to pretend like this never happened! 

Dude, you're standing on shoulders of giants who came before you and released everything under MIT license, but somehow you believe that you and your code are so special that you needs to use a more restrictive license like the AGPL.  Grow up !

**Comment by Lewiscowles1986** [comment]
one word, which an online tool I've posted a link to says is incorrect. Are we going to suggest that I cannot use the alphabet next, or perhaps infer synonymous inflections in other things I have written?

This is not a trial, you are not a judge. Stop wasting your day and mine arguing like a 2-year-old on the basis that I closed your issue, froze it, and won't do as you say because I used a word you think is important...

Now you're dragging other people in.

**Comment by mambax7** [comment]
@Lewiscowles1986 said:
> Are we going to suggest that I cannot use the alphabet next,?

Why are you so childish? The beauty of Open Source is that you can use the code, modify it, give to other people. The only thing that we ask is to respect the respective Open Source licenses. 
Dude, just grow up!

**Comment by Lewiscowles1986** [comment]
As I seem to be the only one providing evidence, rather than pictures, emotive language & what-iffery

From an earlier comment here

> https://www.copyscape.com/compare.php says there is 0% similarity between the two
> 
> https://raw.githubusercontent.com/fvilers/ulid.net/master/Src/UlidNet.Tests/UlidTest.cs
> https://raw.githubusercontent.com/Lewiscowles1986/php-ulid/master/tests/BaseTest.php

From the [JS repo issue](https://github.com/ulid/javascript/issues/61)

https://github.com/ulid/javascript/issues/61#issuecomment-381408398

> @mambax7 I have no affiliation with either project, but you're mistaken on how the licensing works.
> 
> ULID is a spec which is GPL licensed: https://github.com/ulid/spec
> 
> ULID.js is a JavaScript implementation of the spec which is MIT licensed.
> 
> Anyone can implement the spec in any programming programming language they'd like and release > it under any license they choose.
> 
> There is no license violation going on here. @Lewiscowles1986 is free to do as he wants.
> 
> An example of a license violation would be if someone were to fork ULID.js (MIT licensed), modify a > few files and then release something like ULID-2.js under AGPL or another license.

Again from JS repo issue

https://github.com/ulid/javascript/issues/61#issuecomment-381419363

> the ULID PHP > project is not simply using forked code. @Lewiscowles1986 wrote original PHP code based on the GPL-licensed ULID spec.
> 
> Had @Lewiscowles1986 simply taken the source code for ULID.js and made only simple modifications to the JS source to make it work with PHP then there could be a license issue. But it's clear to me looking at the source that ULID.php is all original code and implemented in a totally different way than ULID.js, thus it's an original work based on a GPL spec and the author is free to license as they want.

From OP's own post (imagining I had copied verbatim any of the original code)
https://www.quora.com/Can-I-change-the-license-of-the-MIT-source-code-after-I-made-a-lot-of-changes

> The MIT license requires you to include in the final product the copyright notice and the permission notice ***for the part of code that derives from the MIT-licensed code.***

As the tool I've linked shows given the URL's I've provided (and I'm confident other URLS from my repo being reported with ULID.NET and ULID.JS) there is in-fact no substantially copied code (shows 0% in the tool I've linked).

![input to copyscape](https://user-images.githubusercontent.com/2605791/38851205-a97f5350-420c-11e8-8aa5-f218a57a3f32.png)
![output from copyscape](https://user-images.githubusercontent.com/2605791/38851217-b7701af8-420c-11e8-8e9a-b8d96bf43df2.png)


Now I'm sure OP will be back on this, tagging me in violation of their own CoC, requiring them to not harass in public spaces, keep publshing my online identity to associate it with their campaign, but unless someone has Evidence (not just a single word they fixate upon), then you're all essentially just facilitating more conflict over nothing. 

At this point I'm not even ammending the README.md in my repo to choose my language more carefully, which OP has inferred I have done. This isn't a fork of the .NET code or the JS code. I've not copied any of your code (constants are not code). Check it, then close please.

AND STOP TAGGING ME

**Comment by fvilers** [comment]
OK guys, let's put and end to this. Even if I'd like to know why AGPL specifically from @Lewiscowles1986, it seems that he doesn't want to explain. Let's get back to work!
